#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --mem=30g
##SBATCH --nodelist=compute-0-7
#SBATCH -t 0

python src/main.py \
  --clean_mem_every 5 \
  --reset_output_dir \
  --char_ngram_n 4 \
  --semb="dot_prod" \
  --query_base \
  --trg_no_char \
  --ordered_char_dict \
  --semb_vsize 10000 \
  --output_dir="outputs_VERSION/all-semb-bq-no-spe-8000_ILRL/" \
  --train_src_file_list data/IL_eng/ted-train.mtok.IL,data/tur_eng/ted-train.mtok.tur,data/rus_eng/ted-train.mtok.rus,data/por_eng/ted-train.mtok.por,data/ces_eng/ted-train.mtok.ces \
  --train_trg_file_list  data/IL_eng/ted-train.mtok.spm8000.eng,data/tur_eng/ted-train.mtok.spm8000.eng,data/rus_eng/ted-train.mtok.spm8000.eng,data/por_eng/ted-train.mtok.spm8000.eng,data/ces_eng/ted-train.mtok.spm8000.eng \
  --dev_src_file  data/IL_eng/ted-dev.mtok.IL \
  --dev_trg_file  data/IL_eng/ted-dev.mtok.spm8000.eng \
  --dev_trg_ref  data/IL_eng/ted-dev.mtok.eng \
  --src_vocab_list data/IL_eng/ted-train.mtok.IL.vocab,data/tur_eng/ted-train.mtok.tur.vocab,data/rus_eng/ted-train.mtok.rus.vocab,data/por_eng/ted-train.mtok.por.vocab,data/ces_eng/ted-train.mtok.ces.vocab \
  --trg_vocab_list  data/ILRL_eng/ted-train.mtok.spm8000.eng.vocab \
  --src_char_vocab_from data/IL_eng/ted-train.mtok.IL.ochar4vocab,data/tur_eng/ted-train.mtok.tur.ochar5vocab,data/rus_eng/ted-train.mtok.rus.ochar5vocab,data/por_eng/ted-train.mtok.por.ochar5vocab,data/ces_eng/ted-train.mtok.ces.ochar5vocab \
  --src_char_vocab_size='8000,8000,8000,8000,8000' \
  --trg_char_vocab_from  data/ILRL_eng/ted-train.mtok.spm8000.eng.char4vocab \
  --trg_char_vocab_size='8000' \
  --d_word_vec=128 \
  --d_model=512 \
  --log_every=50 \
  --eval_every=2500 \
  --ppl_thresh=15 \
  --merge_bpe \
  --eval_bleu \
  --cuda \
  --batcher='word' \
  --batch_size 1500 \
  --valid_batch_size=7 \
  --patience 8 \
  --lr_dec 0.95 \
  --dropout 0.3 \
  --max_len 10000 \
  --seed SEED
