#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --mem=15g
##SBATCH --nodelist=compute-0-7
#SBATCH -t 0

#export PYTHONPATH="$(pwd)"
#export CUDA_VISIBLE_DEVICES="1"

python src/main.py \
  --clean_mem_every 5 \
  --reset_output_dir \
  --char_ngram_n 4 \
  --semb="dot_prod" \
  --sep_char_proj \
  --query_base \
  --semb_vsize 10000 \
  --ordered_char_dict \
  --trg_no_char \
  --output_dir="outputs_VERSION/bi-semb-bq-o4000_ILRL/" \
  --data_path data/ILRL_eng/ \
  --train_src_file_list  data/IL_eng/ted-train.mtok.IL,data/RL_eng/ted-train.mtok.RL \
  --train_trg_file_list  data/IL_eng/ted-train.mtok.spm8000.eng,data/RL_eng/ted-train.mtok.spm8000.eng \
  --dev_src_file  data/IL_eng/ted-dev.mtok.IL \
  --dev_trg_file  data/IL_eng/ted-dev.mtok.spm8000.eng \
  --dev_trg_ref  data/IL_eng/ted-dev.mtok.eng \
  --src_vocab_list  data/IL_eng/ted-train.mtok.IL.vocab,data/RL_eng/ted-train.mtok.RL.vocab \
  --trg_vocab_list  data/ILRL_eng/ted-train.mtok.spm8000.eng.vocab,data/ILRL_eng/ted-train.mtok.spm8000.eng.vocab \
  --src_char_vocab_from  data/IL_eng/ted-train.mtok.IL.ochar4vocab,data/RL_eng/ted-train.mtok.RL.ochar4vocab \
  --src_char_vocab_size='4000,4000' \
  --trg_char_vocab_from  data/ILRL_eng/ted-train.mtok.spm8000.eng.ochar4vocab \
  --trg_char_vocab_size='4000' \
  --d_word_vec=128 \
  --d_model=512 \
  --log_every=50 \
  --eval_every=2500 \
  --ppl_thresh=15 \
  --merge_bpe \
  --eval_bleu \
  --cuda \
  --batcher='word' \
  --batch_size 1500 \
  --valid_batch_size=7 \
  --patience 5 \
  --lr_dec 0.8 \
  --dropout 0.3 \
  --max_len 10000 \
  --seed 0
